apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  containers:
    - name: container-1
      image: nginx:latest
    - name: container-2
      image: busybox:latest
      command: ["sleep", "3600"]
